package es.in2.issuer.backend.shared.domain.model.dto;

import es.in2.issuer.backend.signing.domain.model.dto.SigningResult;
import es.in2.issuer.backend.signing.domain.model.SigningType;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SignedDataTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        SigningType expectedType = SigningType.COSE;
        String expectedData = "sampleData";
        // Act
        SigningResult signedData = new SigningResult(expectedType, expectedData);
        // Assert
        assertEquals(expectedType, signedData.type());
        assertEquals(expectedData, signedData.data());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        SigningType expectedType = SigningType.COSE;
        String expectedData = "sampleData";
        // Act
        SigningResult data1 = new SigningResult(expectedType, expectedData);
        SigningResult data2 = new SigningResult(expectedType, expectedData);
        // Assert
        assertEquals(data1, data2); // Tests equals() method generated by Lombok
        assertEquals(data1.hashCode(), data2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}